<?php

namespace ContainerOkGSQxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessDataPersisterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\DataPersister\ProcessDataPersister' shared autowired service.
     *
     * @return \App\Process\DataPersister\ProcessDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/DataPersister/ContextAwareDataPersisterInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/DataPersister/ProcessDataPersister.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerRegistry.php';

        return $container->privates['App\\Process\\DataPersister\\ProcessDataPersister'] = new \App\Process\DataPersister\ProcessDataPersister(new \App\Process\Service\ProcessHandlerRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Install\\Service\\Installation\\InstallActionHandler'] ?? $container->load('getInstallActionHandlerService'));
            yield 1 => ($container->privates['App\\Process\\LegacyHandler\\ACL\\UserACLHandler'] ?? $container->load('getUserACLHandlerService'));
            yield 2 => ($container->privates['App\\Process\\LegacyHandler\\AddContactsToTargetListBulkActionHandler'] ?? $container->load('getAddContactsToTargetListBulkActionHandlerService'));
            yield 3 => ($container->privates['App\\Process\\LegacyHandler\\AddRecordsToTargetListBulkActionHandler'] ?? $container->load('getAddRecordsToTargetListBulkActionHandlerService'));
            yield 4 => ($container->privates['App\\Process\\LegacyHandler\\LinkRelationHandler'] ?? $container->load('getLinkRelationHandlerService'));
            yield 5 => ($container->privates['App\\Process\\LegacyHandler\\ResetPasswordHandler'] ?? $container->load('getResetPasswordHandlerService'));
            yield 6 => ($container->privates['App\\Process\\LegacyHandler\\UnlinkRelationHandler'] ?? $container->load('getUnlinkRelationHandlerService'));
            yield 7 => ($container->privates['App\\Process\\Service\\BulkActions\\CsvExportBulkAction'] ?? $container->load('getCsvExportBulkActionService'));
            yield 8 => ($container->privates['App\\Process\\Service\\BulkActions\\DeleteRecordsBulkAction'] ?? $container->load('getDeleteRecordsBulkActionService'));
            yield 9 => ($container->privates['App\\Process\\Service\\BulkActions\\MassUpdateBulkAction'] ?? $container->load('getMassUpdateBulkActionService'));
            yield 10 => ($container->privates['App\\Process\\Service\\BulkActions\\MergeRecordsBulkAction'] ?? $container->load('getMergeRecordsBulkActionService'));
            yield 11 => ($container->privates['App\\Process\\Service\\BulkActions\\PrintAsPdfBulkAction'] ?? $container->load('getPrintAsPdfBulkActionService'));
            yield 12 => ($container->privates['App\\Process\\Service\\RecordActions\\ChangeLogAction'] ?? $container->load('getChangeLogActionService'));
            yield 13 => ($container->privates['App\\Process\\Service\\RecordActions\\ConvertLeadAction'] ?? $container->load('getConvertLeadActionService'));
            yield 14 => ($container->privates['App\\Process\\Service\\RecordActions\\DeleteRecordAction'] ?? $container->load('getDeleteRecordActionService'));
            yield 15 => ($container->privates['App\\Process\\Service\\RecordActions\\DuplicateRecordAction'] ?? $container->load('getDuplicateRecordActionService'));
            yield 16 => ($container->privates['App\\Process\\Service\\RecordActions\\EditAction'] ?? $container->load('getEditActionService'));
            yield 17 => ($container->privates['App\\Process\\Service\\RecordActions\\MergeDuplicateAction'] ?? $container->load('getMergeDuplicateActionService'));
            yield 18 => ($container->privates['App\\Process\\Service\\RecordActions\\PrintAsPdfAction'] ?? $container->load('getPrintAsPdfActionService'));
        }, 19)), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
