<?php

namespace ContainerOkGSQxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeImagesItemDataProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Themes\DataProvider\ThemeImagesItemDataProvider' shared autowired service.
     *
     * @return \App\Themes\DataProvider\ThemeImagesItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Themes/DataProvider/ThemeImagesItemDataProvider.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Themes/Service/ThemeImageService.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Themes/Service/ThemeImageFinder.php';

        return $container->privates['App\\Themes\\DataProvider\\ThemeImagesItemDataProvider'] = new \App\Themes\DataProvider\ThemeImagesItemDataProvider(new \App\Themes\Service\ThemeImageService($container->parameters['themes.image_paths'], $container->parameters['themes.image_supported_types'], \dirname(__DIR__, 3), new \App\Themes\Service\ThemeImageFinder($container->parameters['themes.image_supported_types'])));
    }
}
