<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOkGSQxx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOkGSQxx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOkGSQxx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOkGSQxx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOkGSQxx\App_KernelProdContainer([
    'container.build_hash' => 'OkGSQxx',
    'container.build_id' => 'c864c117',
    'container.build_time' => 1649156100,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOkGSQxx');
